const routes = {
    home: '/',
    vanphongpham: '/sanpham/vanphongpham',
    dungcuhoctap: '/sanpham/dungcuhoctap',
    butviet: '/sanpham/butviet',
    mythuat: '/sanpham/mythuat',
    dochoi: '/sanpham/dochoi',
    sach: '/sanpham/sach',
    search: '/search',
    live: '/live',
    chitietsanpham: '/sanpham/chitietsanpham',
    imageBaseUrl: '../../asset/images',
    cart: '/cart',
    thongtintaikhoan: '/thongtintaikhoan',
    donhang: '/donhang',
    dathangthanhcong: '/reviewdonhang',
    ketquatimkiem: '/ketquatimkiem',
    login: '/login',
    signup: '/signup',
};
export default routes;
